language: ruby
before_install:
- gem install sinatra
- gem install rspec
- gem install cucumber
- gem install rack-test
- gem install webrat
- gem install rspec
- gem install simplecov
- gem install simplecov-console
script:
- cucumber
- rspec
deploy:
  provider: heroku
  app: cryptic-anchorage-95686
  api_key:
    secure: Q5IiFet9MB89hAZYfn0nRAVpxqIose8XH+n/NO6VtRjETw+3LIBhW5A9Nzl7+eXARh7NE3GTWQy7t0RSqzEClz2Vzhq+KHDwdDZsjDj8sOd8GD0oINAjAOQl0R+29HufK9Oe26RE2INwr2jjM/gbeMIJQHnI711naiSvy2ufzAZnYU3vg+Yin5MIGZthyTR1xI/92IRZLKgulv8KZj7c/PLewOJIp4c67zbqb9CFHi5PMBwEjT0tmxv3ZOqkw17OP6OSXqgJ6jiV2Dk/H5no2K45uK1zH29Zc8GmL0e8M1FSIyaLMs/BAQ9/l/PvnyJ8IZNtvFDWyCFUtz5NyC+sjPV8R3Nn+EAZ6lsGc/jFA2WgVN8TIMTvXgG8vEOXyRAtxWGKGrJbmR4clrejcXgRNilT9a9kyVUcO9R/sC0TzO02Z8TLgW3LGLwt1RUz35MXRaRCvZqvzwCmlTkyw8wNWE2YQy4PPwOrawpZaButHLOM6CQSs7cHT0a0TexjkZ9ia0rQtjlJLwUxvYo0wtYHOgHjW8k6RPSDic+/FBhW7buZD/kAh0fP+trR6MUEVgDgoRAn84UoUXFW/6zATP7sz5ZOujpKIQjocJbvwPMdRwwyVthp6YQL3hydaocwKkOzVyIjpeg9I1wEKS8Ssyc3E3lEZrUvmblek/dOVMUwbkQ=
