language: ruby

before_install:
  - gem install sinatra
  - gem install rspec
  - gem install cucumber
  - gem install rack-test
  - gem install webrat
  - gem install rspec
  - gem install simplecov
  - gem install simplecov-console

script:
- cucumber
- rspec

deploy: &heroku
        provider: heroku
        app: cryptic-anchorage-95686
        api_key: $HEROKU_AUTH_TOKEN
