language: ruby
script:
- cucumber
- rspec
deploy:
  provider: heroku
  api_key:
    secure: I+sHc3zXGQ5boJVIWURQjlSV9MpVo9loCTk/Ugw/TnLC0ANiMcmevAVXc5ByCeVPp4CnUiRRFXK3xwTeN/vImzvBhgzN/igUKv+lPMBQZxWNy7D6rupNPkPLZgt5D0tq8fodkM8Xd3C7sF6CVuRY3+AS836nUk3xsT8rZ7xi0nSK2UF4DZVZGAYWm9Y0LcWvVNRzOvSTInAIAA3P76pLKXp44YOypohqdBFgp5FbouGHuaC7Lp83w4PRTo7ynuEdAz1tSWvjPtcv2DC6VD8KnK1qUrhfr/aiGs7Zj6zF6QVxkG9iFxUeOhJMrxUjmVDIK7yZHjCIKIfjNpntYrG2xtCFlqXOrIBcaW/eGLDoASyGuxWBkByNf/Inq8eUTqc1rT2YB3JldBVNO3IFoSdf/feZho1jZ4B4s+6eEmYiDog3bRgIMWnyXN7iY8huoP3Mr+YAcd5BSA3g9rsGKP3RHnhqAhoqtZo7LgQIds9uiY9UFYoDI9jyFzySaTAFeevwOt7ZXZKwFhhZfg2D36ZgsBvy4Wc3lv/Zc1sWcH4mNDStEo5W9gibvvLCEmtEs5En5r04VW9rIOEhW67t2LbttdAotpaj7nY4e8HW/w+0L8iLuXNhn1Sgxf321lD8mqxbDymdYezBAjjVKbXDbxLun+/oitjdpxYCePAmkgYD3B4=
  app: whispering-gorge-84323
