language: ruby
before_install:
- gem install sinatra
- gem install rspec
- gem install cucumber
- gem install rack-test
- gem install webrat
- gem install rspec
- gem install simplecov
- gem install simplecov-console
script:
- cucumber
- rspec
deploy:
  provider: heroku
  app: cryptic-anchorage-95686
  api_key:
    secure: YTzr0nGAkKAZUSJ6r7EMS0TpEwhEIaEutU2VWqmMBcLfjlmY044ST3RjNgIgeN6U9NYZhEOlQlmtM6GbdcQGyJXajB1pCOeiFQFnzBEFJwekWTyT8+hmJ5ER9+IagjzAjuMvSZhlIpmgXAJxa9PhfMKPZOo4q4TdwxTEnborUIQhgjNjYo+mgasmPWAEAKlEVBAPzyVHf4QorQNSPGNDR8+lRRzOxz9rltJ3xNaRnwTufLvvzG0M1/7WkYXC0N9CJgIYN5lJaF5xtOviEvH0Bp0bhwJXog34Zq6lHkajzhw4LOpHZIxFZ0Lp1YRWWxtwCSW3ul7t/Jgkrlbclbsz4B8zsw8eDjX6Kc5YsUir5r4i6Xjim95VFTNUq+fgt3XMBjOpb7mk2iNiEpGNRvKCql+HRKwBshTK07SEW06Jl8r36BliCXhBLp/GEctM6x9RCiKFBb6HFO2m9BMZHWU0lWnkF5KcQtdej8i1KDz8cbll20ogG8lqoeeY4DPX+4VlzBhP+OlSa/2wcuRrxd24jY/Lds895i5g38OjZnjWMUPrKV43G3S+dQMFOWIy3pZi6nPRD4hxzNTsBYJUqZKj+qH8W7qk6bbQ7dYKJlB7VXj5E60n3P9HDRnMNU0pgiM5N8kebQzMbuGSRxhVD/o9dWPRoQV6lQgU0iA3y3WwODc=
