require './lib/room'
class Map
	def initialize
		@numberCols = 0
    	@numberRows = 0
    	@rooms=Array.new(1)
    	for i in 0..1
      		@rooms[i] = Array.new(1)
    	end
	end

	def setNumberCols(numberCols)
    	@numberCols = numberCols
  	end

  	def setNumberRows(numberRows)
    	@numberRows = numberRows
  	end

  	def getNumberCols
    	return @numberCols
  	end

  	def getNumberRows
    	return @numberRows
  	end

  	def createDefaultSmallMap
	    @numberRows = 4
	    @numberCols = 4
	    generateMap(@numberRows,@numberCols)
	    generateWallsDefaultSmallMap
  	end

  	def createDefaultMediumMap
	    @numberRows = 8
	    @numberCols = 8
	    generateMap(@numberRows,@numberCols)
	    generateWallsDefaultMediumMap
  	end

  	def createDefaultBigMap
	    @numberRows = 12
	    @numberCols = 12
	    generateMap(@numberRows,@numberCols)
	    generateWallsDefaultBigMap
  	end

  	def createEditedMap(numberRows,numberCols)
    	@numberCols = numberCols
    	@numberRows = numberRows
    	generateMap(@numberRows,@numberCols)
  	end

  	def generateMap(numberRows,numberCols)
    	@rooms=Array.new(numberRows)
    	for i in 0..(numberRows - 1)
      		@rooms[i] = Array.new(numberCols - 1)
    	end
    	for i in 0..(numberRows - 1)
      		for j in 0..(numberCols - 1)
        		@rooms[i][j] = Room.new
     		end
    	end
  	end

  	def getRoom(positionX,positionY)
    	return @rooms[positionX][positionY]
  	end

  	def setRoom(room,positionX,positionY)
    	@rooms[positionX][positionY]=room
  	end

  	def quantityOfRooms
    	return @numberRows*@numberCols
  	end

  	def generateWallsDefaultSmallMap
	    @room=getRoom(0,0)
	    @room.openEntrySouth
	    @room.openEntryEast
	    setRoom(@room,0,0)
	    @room=getRoom(0,1)
	    @room.openEntryNorth
	    setRoom(@room,0,1)
	    @room=getRoom(0,2)
	    @room.openEntryEast
	    setRoom(@room,0,2)
	    @room=getRoom(0,3)
	    @room.openEntryEast
	    setRoom(@room,0,3)
	    @room=getRoom(1,0)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,1,0)
	    @room=getRoom(1,1)
	    @room.openEntryEast
	    @room.setArrowStay
	    setRoom(@room,1,1)
	    @room=getRoom(1,2)
	    @room.openEntrySouth
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,1,2)
	    @room=getRoom(1,3)
	    @room.openEntryNorth
	    @room.openEntryWest
	    setRoom(@room,1,3)
	    @room=getRoom(2,0)
	    @room.openEntrySouth
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,2,0)
	    @room=getRoom(2,1)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,2,1)
	    @room=getRoom(2,2)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,2,2)
	    @room=getRoom(2,3)
	    @room.openEntryNorth
	    setRoom(@room,2,3)
	    @room=getRoom(3,0)
	    @room.openEntrySouth
	    @room.openEntryWest
	    @room.setBreezeStay
	    setRoom(@room,3,0)
	    @room=getRoom(3,1)
	    @room.openEntryNorth
	    @room.setWaterWellStay
	    setRoom(@room,3,1)
	    @room=getRoom(3,2)
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,3,2)
	    @room=getRoom(3,3)
	    @room.openEntryNorth
	    setRoom(@room,3,3)
  	end

  	def generateWallsDefaultMediumMap
	    @room=getRoom(0,0)
	    @room.openEntryEast
	    setRoom(@room,0,0)
	    @room=getRoom(1,0)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,0)
	    @room=getRoom(2,0)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,2,0)
	    @room=getRoom(3,0)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,3,0)
	    @room=getRoom(5,0)
	    @room.openEntryEast
	    @room.openEntrySouth
	    setRoom(@room,5,0)
	    @room=getRoom(6,0)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,0)
	    @room=getRoom(7,0)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,7,0)
	    @room=getRoom(0,1)
	    @room.openEntrySouth
	    setRoom(@room,0,1)
	    @room=getRoom(1,1)
	    @room.openEntryNorth
	    setRoom(@room,1,1)
	    @room=getRoom(2,1)
	    @room.openEntrySouth
	    setRoom(@room,2,1)
	    @room=getRoom(3,1)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryEast
	    setRoom(@room,3,1)
	    @room=getRoom(4,1)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,4,1)
	    @room=getRoom(5,1)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,1)
	    @room=getRoom(6,1)
	    @room.openEntrySouth
	    setRoom(@room,6,1)
	    @room=getRoom(7,1)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,7,1)
	    @room=getRoom(0,2)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    @room.openEntryEast
	    setRoom(@room,0,2)
	    @room=getRoom(1,2)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,2)
	    @room=getRoom(2,2)
	    @room.openEntryNorth
	    @room.openEntryWest
	    setRoom(@room,2,2)
	    @room=getRoom(3,2)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,3,2)
	    @room=getRoom(4,2)
	    @room.openEntrySouth
	    setRoom(@room,4,2)
	    @room=getRoom(5,2)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,5,2)
	    @room=getRoom(6,2)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,6,2)
	    @room=getRoom(7,2)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,7,2)
	    @room=getRoom(0,3)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    setRoom(@room,0,3)
	    @room=getRoom(1,3)
	    @room.openEntryEast
	    setRoom(@room,1,3)
	    @room=getRoom(2,3)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,3)
	    @room=getRoom(3,3)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,3,3)
	    @room=getRoom(4,3)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,4,3)
	    @room=getRoom(5,3)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,5,3)
	    @room=getRoom(6,3)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,6,3)
	    @room=getRoom(7,3)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,7,3)
	    @room=getRoom(0,4)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    setRoom(@room,0,4)
	    @room=getRoom(2,4)
	    @room.openEntrySouth
	    setRoom(@room,2,4)
	    @room=getRoom(3,4)
	    @room.openEntryNorth
	    setRoom(@room,3,4)
	    @room=getRoom(4,4)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,4,4)
	    @room=getRoom(5,4)
	    @room.openEntryNorth
	    setRoom(@room,5,4)
	    @room=getRoom(6,4)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,6,4)
	    @room=getRoom(7,4)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,7,4)
	    @room=getRoom(0,5)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    setRoom(@room,0,5)
	    @room=getRoom(1,5)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,1,5)
	    @room=getRoom(2,5)
	    @room.openEntrySouth
	    @room.openEntryWest
	    @room.openEntryEast
	    @room.openEntryNorth
	    setRoom(@room,2,5)
	    @room=getRoom(3,5)
	    @room.openEntryWest
	    @room.openEntrySouth
	    @room.openEntryEast
	    setRoom(@room,3,5)
	    @room=getRoom(4,5)
	    @room.openEntryEast
	    @room.openEntryWest
	    @room.openEntrySouth
	    @room.openEntryNorth
	    setRoom(@room,4,5)
	    @room=getRoom(5,5)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,5,5)
	    @room=getRoom(6,5)
	    @room.openEntryNorth
	    @room.openEntryWest
	    setRoom(@room,6,5)
	    @room=getRoom(7,5)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    setRoom(@room,7,5)
	    @room=getRoom(0,6)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    setRoom(@room,0,6)
	    @room=getRoom(2,6)
	    @room.openEntrySouth
	    @room.openEntryNorth
	    @room.openEntryEast
	    setRoom(@room,2,6)
	    @room=getRoom(3,6)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,3,6)
	    @room=getRoom(4,6)
	    @room.openEntryEast
	    @room.openEntryNorth
	    setRoom(@room,4,6)
	    @room=getRoom(5,6)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,5,6)
	    @room=getRoom(6,6)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,6)
	    @room=getRoom(7,6)
	    @room.openEntryNorth
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,7,6)
	    @room=getRoom(0,7)
	    @room.openEntryNorth
	    @room.openEntryEast
	    setRoom(@room,0,7)
	    @room=getRoom(1,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,7)
	    @room=getRoom(2,7)
	    @room.openEntryNorth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,7)
	    @room=getRoom(3,7)
	    @room.openEntryNorth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,3,7)
	    @room=getRoom(4,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,4,7)
	    @room=getRoom(5,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,5,7)
	    @room=getRoom(6,7)
	    @room.openEntryWest
	    setRoom(@room,6,7)
	    @room=getRoom(7,7)
	    @room.openEntryNorth
	    setRoom(@room,7,7)
  	end

  	def generateWallsDefaultBigMap
	    @room=getRoom(0,0)
	    @room.openEntryEast
	    setRoom(@room,0,0)
	    @room=getRoom(1,0)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,0)
	    @room=getRoom(2,0)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,0)
	    @room=getRoom(3,0)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,0)
	    @room=getRoom(4,0)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,0)
	    @room=getRoom(5,0)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,0)
	    @room=getRoom(6,0)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,0)
	    @room=getRoom(7,0)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,0)
	    @room=getRoom(8,0)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,0)
	    @room=getRoom(9,0)
	    @room.openEntrySouth
	    setRoom(@room,9,0)
	    @room=getRoom(10,0)
	    @room.openEntrySouth
	    setRoom(@room,10,0)


	    @room=getRoom(0,1)
	    @room.openEntryEast
	    setRoom(@room,0,1)
	    @room=getRoom(1,1)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,1)
	    @room=getRoom(2,1)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,1)
	    @room=getRoom(3,1)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,1)
	    @room=getRoom(4,1)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,1)
	    @room=getRoom(5,1)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,1)
	    @room=getRoom(6,1)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,1)
	    @room=getRoom(7,1)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,1)
	    @room=getRoom(8,1)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,1)
	    @room=getRoom(9,1)
	    @room.openEntrySouth
	    setRoom(@room,9,1)
	    @room=getRoom(10,1)
	    @room.openEntrySouth
	    setRoom(@room,10,1)
	    @room=getRoom(11,1)
	    @room.openEntrySouth
	    setRoom(@room,11,1)



	    @room=getRoom(0,2)
	    @room.openEntryEast
	    setRoom(@room,0,2)
	    @room=getRoom(1,2)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,2)
	    @room=getRoom(2,2)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,2)
	    @room=getRoom(3,2)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,2)
	    @room=getRoom(4,2)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,2)
	    @room=getRoom(5,2)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,2)
	    @room=getRoom(6,2)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,2)
	    @room=getRoom(7,2)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,2)
	    @room=getRoom(8,2)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,2)
	    @room=getRoom(9,2)
	    @room.openEntrySouth
	    setRoom(@room,9,2)
	    @room=getRoom(10,2)
	    @room.openEntrySouth
	    setRoom(@room,10,2)
	    @room=getRoom(11,2)
	    @room.openEntrySouth
	    setRoom(@room,11,2)



	    @room=getRoom(0,3)
	    @room.openEntryEast
	    setRoom(@room,0,3)
	    @room=getRoom(1,3)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,3)
	    @room=getRoom(2,3)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,3)
	    @room=getRoom(3,3)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,3)
	    @room=getRoom(4,3)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,3)
	    @room=getRoom(5,3)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,3)
	    @room=getRoom(6,3)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,3)
	    @room=getRoom(7,3)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,3)
	    @room=getRoom(8,3)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,3)
	    @room=getRoom(9,3)
	    @room.openEntrySouth
	    setRoom(@room,9,3)
	    @room=getRoom(10,3)
	    @room.openEntrySouth
	    setRoom(@room,10,3)
	    @room=getRoom(11,3)
	    @room.openEntrySouth
	    setRoom(@room,11,3)

	    @room=getRoom(0,4)
	    @room.openEntryEast
	    setRoom(@room,0,4)
	    @room=getRoom(1,4)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,4)
	    @room=getRoom(2,4)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,4)
	    @room=getRoom(3,4)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,4)
	    @room=getRoom(4,4)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,4)
	    @room=getRoom(5,4)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,4)
	    @room=getRoom(6,4)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,4)
	    @room=getRoom(7,4)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,4)
	    @room=getRoom(8,4)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,4)
	    @room=getRoom(9,4)
	    @room.openEntrySouth
	    setRoom(@room,9,4)
	    @room=getRoom(10,4)
	    @room.openEntrySouth
	    setRoom(@room,10,4)
	    @room=getRoom(11,4)
	    @room.openEntrySouth
	    setRoom(@room,11,4)

	    @room=getRoom(0,4)
	    @room.openEntryEast
	    setRoom(@room,0,4)
	    @room=getRoom(1,4)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,4)
	    @room=getRoom(2,4)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,4)
	    @room=getRoom(3,4)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,4)
	    @room=getRoom(4,4)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,4)
	    @room=getRoom(5,4)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,4)
	    @room=getRoom(6,4)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,4)
	    @room=getRoom(7,4)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,4)
	    @room=getRoom(8,4)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,4)
	    @room=getRoom(9,4)
	    @room.openEntrySouth
	    setRoom(@room,9,4)
	    @room=getRoom(10,4)
	    @room.openEntrySouth
	    setRoom(@room,10,4)
	    @room=getRoom(11,4)
	    @room.openEntrySouth
	    setRoom(@room,11,4)

	    @room=getRoom(0,5)
	    @room.openEntryEast
	    setRoom(@room,0,5)
	    @room=getRoom(1,5)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,5)
	    @room=getRoom(2,5)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,5)
	    @room=getRoom(3,5)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,5)
	    @room=getRoom(4,5)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,5)
	    @room=getRoom(5,5)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,5)
	    @room=getRoom(6,5)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,5)
	    @room=getRoom(7,5)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,5)
	    @room=getRoom(8,5)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,5)
	    @room=getRoom(9,5)
	    @room.openEntrySouth
	    setRoom(@room,9,6)
	    @room=getRoom(10,6)
	    @room.openEntrySouth
	    setRoom(@room,10,6)
	    @room=getRoom(11,6)
	    @room.openEntrySouth
	    setRoom(@room,11,6)

	    @room=getRoom(0,7)
	    @room.openEntryEast
	    setRoom(@room,0,7)
	    @room=getRoom(1,7)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,7)
	    @room=getRoom(2,7)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,7)
	    @room=getRoom(3,7)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,7)
	    @room=getRoom(4,7)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,7)
	    @room=getRoom(5,7)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,7)
	    @room=getRoom(6,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,7)
	    @room=getRoom(7,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,7)
	    @room=getRoom(8,7)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,7)
	    @room=getRoom(9,7)
	    @room.openEntrySouth
	    setRoom(@room,9,7)
	    @room=getRoom(10,7)
	    @room.openEntrySouth
	    setRoom(@room,10,7)
	    @room=getRoom(11,7)
	    @room.openEntrySouth
	    setRoom(@room,11,7)

	    @room=getRoom(0,7)
	    @room.openEntryEast
	    setRoom(@room,0,7)
	    @room=getRoom(1,7)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,7)
	    @room=getRoom(2,7)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,7)
	    @room=getRoom(3,7)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,7)
	    @room=getRoom(4,7)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,7)
	    @room=getRoom(5,7)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,7)
	    @room=getRoom(6,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,7)
	    @room=getRoom(7,7)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,7)
	    @room=getRoom(8,7)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,7)
	    @room=getRoom(9,7)
	    @room.openEntrySouth
	    setRoom(@room,9,7)
	    @room=getRoom(10,7)
	    @room.openEntrySouth
	    setRoom(@room,10,7)
	    @room=getRoom(11,7)
	    @room.openEntrySouth
	    setRoom(@room,11,7)

	    @room=getRoom(0,8)
	    @room.openEntryEast
	    setRoom(@room,0,8)
	    @room=getRoom(1,8)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,8)
	    @room=getRoom(2,8)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,8)
	    @room=getRoom(3,8)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,9)
	    @room=getRoom(4,9)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,9)
	    @room=getRoom(5,9)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,9)
	    @room=getRoom(6,9)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,9)
	    @room=getRoom(7,9)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,9)
	    @room=getRoom(8,9)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,9)
	    @room=getRoom(9,9)
	    @room.openEntrySouth
	    setRoom(@room,9,9)
	    @room=getRoom(10,9)
	    @room.openEntrySouth
	    setRoom(@room,10,9)
	    @room=getRoom(11,9)
	    @room.openEntrySouth
	    setRoom(@room,11,9)

	    @room=getRoom(0,10)
	    @room.openEntryEast
	    setRoom(@room,0,10)
	    @room=getRoom(1,10)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,10)
	    @room=getRoom(2,10)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,10)
	    @room=getRoom(3,10)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,10)
	    @room=getRoom(4,10)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,10)
	    @room=getRoom(5,10)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,10)
	    @room=getRoom(6,10)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,10)
	    @room=getRoom(7,10)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,10)
	    @room=getRoom(8,10)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,10)
	    @room=getRoom(9,10)
	    @room.openEntrySouth
	    setRoom(@room,9,10)
	    @room=getRoom(10,10)
	    @room.openEntrySouth
	    setRoom(@room,10,10)
	    @room=getRoom(11,10)
	    @room.openEntrySouth
	    setRoom(@room,11,10)

	    @room=getRoom(0,11)
	    @room.openEntryEast
	    setRoom(@room,0,11)
	    @room=getRoom(1,11)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,1,11)
	    @room=getRoom(2,11)
	    @room.openEntrySouth
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,2,11)
	    @room=getRoom(3,11)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,3,11)
	    @room=getRoom(4,11)
	    @room.openEntryWest
	    @room.openEntryEast
	    setRoom(@room,4,11)
	    @room=getRoom(5,11)
	    @room.openEntryEast
	    @room.openEntrySouth
	    @room.openEntryWest
	    setRoom(@room,5,11)
	    @room=getRoom(6,11)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,6,11)
	    @room=getRoom(7,11)
	    @room.openEntryEast
	    @room.openEntryWest
	    setRoom(@room,7,11)
	    @room=getRoom(8,11)
	    @room.openEntryWest
	    @room.openEntrySouth
	    setRoom(@room,8,11)
	    @room=getRoom(9,11)
	    @room.openEntrySouth
	    setRoom(@room,9,11)
	    @room=getRoom(10,11)
	    @room.openEntrySouth
	    setRoom(@room,10,11)
	    @room=getRoom(11,11)
	    @room.openEntrySouth
	    setRoom(@room,11,11)
  	end

end